sudo: require
language: cpp
compiler: gcc
dist: bionic

before_install: sudo chmod +x installdependencies.sh && ./installdependencies.sh 


script: cd code && qmake && make && cd - && cd code/unitTests && chmod +x run_sw_tests.sh && ./run_sw_tests.sh
