sudo: require
language: cpp
compiler: gcc
dist: bionic

before_install: 
- sudo apt-get install python3
- sudo snap install pypy3 --classic
- sudo chmod +x installdependencies.sh 
- ./installdependencies.sh 

script: 
- cd code 
- qmake 
- make 
- cd unitTests
- chmod +x run_sw_tests.sh
- ./run_sw_tests.sh
