sudo: require
language: cpp
compiler: gcc
dist: bionic

before_install: 
- sudo chmod +x installdependencies.sh
- ./installdependencies.sh #install dependencies

script:
- sudo chmod +x build.sh
- ./build.sh
